drop schema if exists store cascade;

create schema store;

create table if not exists store.product (
    id integer generated by default as identity(start with 1) primary key,
    name varchar(60) not null unique,
    price integer not null
);
